version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: productitask-app
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://postgres:postgres@db:5432/productitask
      - SESSION_SECRET=production_session_secret
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs

  db:
    image: postgres:14-alpine
    container_name: productitask-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=productitask
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: